export const INCREMENT_ACTIVE_STEP = "INCREMENT_ACTIVE_STEP";
export const DECREMENT_ACTIVE_STEP = "DECREMENT_ACTIVE_STEP";

export const SUBMIT_FORM = "SUBMIT_FORM";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
